### PR TITLE
GRC-Helper python3 support.

### PR DESCRIPTION
**Pull request by vanflux**
- Using python3 on grc-helper if present.

### CODE REVIEW

**Comment by ArthurSudbrackIbarra** [comment]
@vanflux 

image

I got this error when testing the modified grc helper script.

**Comment by vanflux** [comment]
Can you use `python3` command or it's just `python`?
What prints when you run `Get-Command python3` on powershell?

**Comment by ArthurSudbrackIbarra** [comment]
> Can you use `python3` command or it's just `python`? What prints when you run `Get-Command python3` on powershell?

@vanflux It's just python on my Windows. 

image

However, your command does not result in an error when I run it in Powershell.

**Comment by vanflux** [comment]
When you use `python3` command, do you get python not found error too?

**Comment by vanflux** [comment]
I changed the method of detecting python3, maybe now it works.

**Comment by ArthurSudbrackIbarra** [comment]
@vanflux It worked! Merged.

**Pull request merged**
